### ISSUE TITLE
invalid UTF-8 label value

### ISSUE THREAD

**Issue by dthpulse** [sflow-rt/prometheus#1]
Hi
some sflow labels aren't in UTF-8 format, causing Prometheus to report target as down or missing.

```
sflow_country_bps{src="CZ Czechia",dst="RE Réunion"} 
```

Can it be fixed by converting labels to UTF-8?

Or is there some other workaround?

Thank you

**Comment by sflow-rt** [comment]
I changed the default character encoding for text in sFlow-RT to UTF-8, so upgrading to sFlow-RT version 3.0-1638 should resolve the issue. The docker hub images have also been updated, so if you are using Docker, a docker pull should fix the issue. Please confirm that the encoding problem with Prometheus labels has been resolved.

**Comment by dthpulse** [comment]
Hi, looks to be fixed! Thank you!
